//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RateMyApp.Core.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RateMyApp.Core.Resources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later....
        /// </summary>
        public static string RateMyAppCancelText {
            get {
                return ResourceManager.GetString("RateMyAppCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app@hotmail.com.
        /// </summary>
        public static string RateMyAppFeedbackEmail {
            get {
                return ResourceManager.GetString("RateMyAppFeedbackEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you like the app plese let us know!.
        /// </summary>
        public static string RateMyAppHeader {
            get {
                return ResourceManager.GetString("RateMyAppHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We hope that you enjoy using our app, if so please let us know as this will surtainly motivate us to improve it :) .
        /// </summary>
        public static string RateMyAppText {
            get {
                return ResourceManager.GetString("RateMyAppText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email feedback.
        /// </summary>
        public static string RateMyAppThridOptionText {
            get {
                return ResourceManager.GetString("RateMyAppThridOptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Now!.
        /// </summary>
        public static string RateMyAppYesText {
            get {
                return ResourceManager.GetString("RateMyAppYesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
    }
}
